#!/bin/sh
#
# Initialize Buildhistory for this branch
#
# Called with $1 - The buildhistory directory
#             $2 - The remote repository url
#             $3 - The remote branch name
#
BUILDHISTDIR=$1
REMOTEREPO=$2
REMOTEBRANCH=$3

echo BH $@

exit 0

# Example code dumped from an existing nightly-arm buildhistory step for reference

if [ ! -d $BUILDHISTDIR ]; then
    mkdir -p $BUILDHISTDIR
    git init $BUILDHISTDIR
fi

if ! git ls-remote --exit-code $REMOTEREPO refs/heads/$REMOTEBRANCH > /dev/null; then
    cd $BUILDHISTDIR
    echo 'Initializing Repo' >> README
    git checkout -b $REMOTEBRANCH
    git add README
    git commit -s -m 'Initializing Repo'
    git push -q $REMOTEREPO $REMOTEBRANCH:$REMOTEBRANCH
fi
