#!/bin/sh
#
# Initialize Buildhistory for this branch
#
# Called with $1 - The buildhistory directory
#             $2 - The remote repository url
#             $3 - The remote branch name
#             $4 - The remote branch name to base from
#
BUILDHISTDIR=$1
REMOTEREPO=$2
REMOTEBRANCH=$3
BASEBRANCH=$4

if [ ! -d $BUILDHISTDIR ]; then
    mkdir -p $BUILDHISTDIR
    git init $BUILDHISTDIR
fi

cd $BUILDHISTDIR
git checkout -b $REMOTEBRANCH

if git ls-remote --exit-code $REMOTEREPO refs/heads/$BASEBRANCH > /dev/null; then
    git fetch --depth=5 $REMOTEREPO refs/heads/$BASEBRANCH:refs/remotes/$BASEBRANCH
    git reset refs/remotes/$BASEBRANCH --hard
else
    echo 'Initializing Repo' >> README
    git add README
    git commit -s -m 'Initializing Buildhistory'
fi
git tag ab-fetchrev
