#!/usr/bin/env python3
import json, os.path, collections
import sys
import argparse
import subprocess
import tempfile
import shlex

args = argparse.ArgumentParser(description="Update Patch Metrics")
args.add_argument("-j", "--json", help="update JSON")
args.add_argument("-s", "--patchscript", help="review script to use")
args.add_argument("-r", "--repo", help="target repository to scan")
args.add_argument("-d", "--dir", help="directory in the repository to scan", default=".")
args.add_argument("-e", "--extraargs", help="extra arguments to give to the review script")
args = args.parse_args()

print("Running patchmetrics-update")

with tempfile.TemporaryDirectory(prefix="patchmetrics-") as tempdir:
    subprocess.check_call(["git", "clone", args.repo, tempdir])
    repo_revisions = subprocess.check_output(["git", "rev-list", "--since", "1274625106", "origin/master"], universal_newlines=True, cwd=tempdir).strip().split()
    try:
        with open(args.json) as f:
            data = json.load(f)
    except FileNotFoundError:
        data = []


    seen = set()
    for i in data:
        if "commit" in i:
            seen.add(i["commit"])

    repo_revisions = repo_revisions[:10] # XXX
    needed_revisions = set(repo_revisions) - seen

    print("Need to scan revisions %s" % str(needed_revisions))

    print("Needed %s revisions (%s and %s in data sets)" % (len(needed_revisions), len(seen), len(repo_revisions)))

    for rev in needed_revisions:
        print("Processing %s" % rev)
        subprocess.check_output(["git", "reset", "--hard", rev], universal_newlines=True, cwd=tempdir).strip()

        command = [args.patchscript, "-j", args.json]
        target_dir = os.path.join(tempdir, args.dir)
        command.append(target_dir)
        if args.extraargs:
            command.extend(shlex.split(args.extraargs))
        subprocess.check_call(command)

    newdata = []
    with open(args.json) as f:
        data = json.load(f)

    for i in data:
        if "commit" not in i:
            print("Ignoring data with no commit %s" % str(i))
            continue

        if "commit_count" not in i:
            i['commit_count'] = subprocess.check_output(["git", "rev-list", "--count", i['commit']], universal_newlines=True, cwd=tempdir).strip()
        if "recipe_count" not in i:
            subprocess.check_output(["git", "reset", "--hard", i['commit']], universal_newlines=True, cwd=tempdir).strip()
            find_dir = os.path.join(tempdir,args.dir)
            i['recipe_count'] = subprocess.check_output([f"find {find_dir} -type f -name *.bb  | wc -l"], shell=True, universal_newlines=True, cwd=tempdir).strip()

        #print(i['commit_count'] + " " + i['recipe_count'])

        newdata.append(i)

    with open(args.json, "w") as f:
        json.dump(newdata, f, sort_keys=True, indent="\t")

print("Finished patchmetrics-update")

