#!/bin/bash
WORKDIR=$1
DEST=$2
target=$3

md5sums(){
    dest=$1
    for x in `find $dest -maxdepth 5 -type f`; do 
        if [ ${x##*.} != md5sum ]; then 
            md5sum $x >> $x.md5sum
        fi
    done
}

TMPDIR=$WORKDIR/tmp

case "$target" in
    "qemuarm"|"qemuarm64"|"qemumips64"|"qemumips"|"qemuppc"|"qemux86"|"qemux86-64"|"edgerouter"|"mpc8315e-rdb"|"genericx86"|"genericx86-64"|"beaglebone")
        mkdir -p $DEST/toolchain/i686
        mkdir -p $DEST/toolchain/x86_64
        md5sums $TMPDIR/deploy/sdk
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/sdk/poky-*i686-core-image* $DEST/toolchain/i686
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/sdk/poky-*x86_64-core-image* $DEST/toolchain/x86_64
        ;;
esac

case "$target" in
    "build-appliance")
        mkdir -p $DEST/build-appliance
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemux86-64/*.zip $DEST/build-appliance
        ;;
    "buildtools")
        mkdir -p $DEST/buildtools
        mkdir -p $DEST/toolchain/i686
        mkdir -p $DEST/toolchain/x86_64
        md5sums $TMPDIR/deploy/sdk
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/sdk/*buildtools* $DEST/buildtools
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/sdk/i686-nativesdk-libc* $DEST/toolchain/i686
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/sdk/x86_64-nativesdk-libc* $DEST/toolchain/x86_64
        ;;
    "qemuarm64")
        mkdir -p $DEST/machines/qemu/qemuarm64
        md5sums $TMPDIR/deploy/images/qemuarm64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuarm64/*qemuarm64* $DEST/machines/qemu/qemuarm64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuarm64/*Image* $DEST/machines/qemu/qemuarm64
        ;;
    "qemuarm")
        mkdir -p $DEST/machines/qemu/qemuarm
        md5sums $TMPDIR/deploy/images/qemuarm
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuarm/*qemuarm* $DEST/machines/qemu/qemuarm
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuarm/*Image* $DEST/machines/qemu/qemuarm
        ;;
    "beaglebone")
        mkdir -p $DEST/machines/beaglebone-yocto
        md5sums $TMPDIR/deploy/images/beaglebone-yocto
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/beaglebone-yocto/*Image* $DEST/machines/beaglebone-yocto
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/beaglebone-yocto/*u-boot* $DEST/machines/beaglebone-yocto
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/beaglebone-yocto/*beaglebone-yocto* $DEST/machines/beaglebone-yocto
        ;;
    "qemuarm-lsb")
        mkdir -p $DEST/machines/qemu/qemuarm-lsb
        md5sums $TMPDIR/deploy/images/qemuarm
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuarm/*qemuarm* $DEST/machines/qemu/qemuarm-lsb
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuarm/*Image* $DEST/machines/qemu/qemuarm-lsb
        ;;
    "beaglebone-lsb")
        mkdir -p $DEST/machines/beaglebone-yocto-lsb
        md5sums $TMPDIR/deploy/images/beaglebone-yocto
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/beaglebone-yocto/*Image* $DEST/machines/beaglebone-yocto-lsb
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/beaglebone-yocto/*u-boot* $DEST/machines/beaglebone-yocto-lsb
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/beaglebone-yocto/*beaglebone-yocto* $DEST/machines/beaglebone-yocto-lsb
        ;;
    "qemumips64")
        mkdir -p $DEST/machines/qemu/qemumips64
        md5sums $TMPDIR/deploy/images/qemumips64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemumips64/*qemumips64* $DEST/machines/qemu/qemumips64
        ;;
    "qemumips")
        mkdir -p $DEST/machines/qemu/qemumips
        md5sums $TMPDIR/deploy/images/qemumips
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemumips/*qemumips* $DEST/machines/qemu/qemumips
        ;;
    "edgerouter")
        mkdir -p $DEST/machines/edgerouter
        md5sums $TMPDIR/deploy/images/edgerouter
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/edgerouter/*edgerouter* $DEST/machines/edgerouter
        ;;
    "qemumips-lsb")
        mkdir -p $DEST/machines/qemu/qemumips-lsb
        md5sums $TMPDIR/deploy/images/qemumips
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemumips/*qemumips* $DEST/machines/qemu/qemumips-lsb
        ;;
    "edgerouter-lsb")
        mkdir -p $DEST/machines/edgerouter-lsb
        md5sums $TMPDIR/deploy/images/edgerouter
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/edgerouter/*edgerouter* $DEST/machines/edgerouter-lsb
        ;;
    "qemuppc")
        mkdir -p $DEST/machines/qemu/qemuppc
        md5sums $TMPDIR/deploy/images/qemuppc
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuppc/*qemuppc* $DEST/machines/qemu/qemuppc
        ;;
    "mpc8315e-rdb")
        mkdir -p $DEST/machines/mpc8315e-rdb
        md5sums $TMPDIR/deploy/images/mpc8315e-rdb
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/mpc8315e-rdb/*mpc8315* $DEST/machines/mpc8315e-rdb
        ;;
    "qemuppc-lsb")
        mkdir -p $DEST/machines/qemu/qemuppc-lsb
        md5sums $TMPDIR/deploy/images/qemuppc
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemuppc/*qemuppc* $DEST/machines/qemu/qemuppc-lsb
        ;;
    "mpc8315e-rdb-lsb")
        mkdir -p $DEST/machines/mpc8315e-rdb-lsb
        md5sums $TMPDIR/deploy/images/mpc8315e-rdb
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/mpc8315e-rdb/*mpc8315* $DEST/machines/mpc8315e-rdb-lsb
        ;;
    "wic")
        mkdir -p $DEST/machines/qemu/qemux86
        md5sums $TMPDIR/deploy/wic_images/qemux86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/qemux86/*/*/*.direct $DEST/machines/qemu/qemux86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/qemux86/*/*/*.direct.md5sum $DEST/machines/qemu/qemux86
        mkdir -p $DEST/machines/genericx86
        md5sums $TMPDIR/deploy/wic_images/genericx86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/genericx86/*/*/*.direct $DEST/machines/genericx86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/genericx86/*/*/*.direct.md5sum $DEST/machines/genericx86
        mkdir -p $DEST/machines/qemu/qemux86-64
        md5sums $TMPDIR/deploy/wic_images/qemux86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/qemux86-64/*/*/*.direct $DEST/machines/qemu/qemux86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/qemux86-64/*/*/*.direct.md5sum $DEST/machines/qemu/qemux86-64
        mkdir -p $DEST/machines/genericx86-64
        md5sums $TMPDIR/deploy/wic_images/genericx86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/genericx86-64/*/*/*.direct $DEST/machines/genericx86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/wic_images/genericx86-64/*/*/*.direct.md5sum $DEST/machines/genericx86-64
        ;;
    "qemux86-64")
        mkdir -p $DEST/machines/qemu/qemux86-64
        md5sums $TMPDIR/deploy/images/qemux86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemux86-64/*qemux86-64* $DEST/machines/qemu/qemux86-64
        ;;
    "genericx86-64")
        mkdir -p $DEST/machines/genericx86-64
        md5sums $TMPDIR/deploy/images/genericx86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/genericx86-64/*genericx86-64* $DEST/machines/genericx86-64
        ;;
    "qemux86-64-lsb")
        mkdir -p $DEST/machines/qemu/qemux86-64-lsb
        md5sums $TMPDIR/deploy/images/qemux86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemux86-64/*qemux86-64* $DEST/machines/qemu/qemux86-64-lsb
        ;;
    "genericx86-64-lsb")
        mkdir -p $DEST/machines/genericx86-64-lsb
        md5sums $TMPDIR/deploy/images/genericx86-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/genericx86-64/*genericx86-64* $DEST/machines/genericx86-64-lsb
        ;;
    "nightly-x86-64-bsp")
        rm -rf $DEST/$target/images/intel-corei7-64/*
        mkdir -p $DEST/$target/images/intel-corei7-64
        md5sums $TMPDIR/deploy/images/intel-corei7-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/intel-corei7-64/bzImage* $DEST/$target/images/intel-corei7-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/intel-corei7-64/*core-image-sato-sdk-intel-corei7-64*tar* $DEST/$target/images/intel-corei7-64
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/intel-corei7-64/*modules-* $DEST/$target/images/intel-corei7-64
        ;;
    "qemux86")
        mkdir -p $DEST/machines/qemu/qemux86
        md5sums $TMPDIR/deploy/images/qemux86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemux86/*qemux86* $DEST/machines/qemu/qemux86
        ;;
    "genericx86")
        mkdir -p $DEST/machines/genericx86
        md5sums $TMPDIR/deploy/images/genericx86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/genericx86/*genericx86* $DEST/machines/genericx86
        ;;
    "qemux86-lsb")
        mkdir -p $DEST/machines/qemu/qemux86-lsb
        md5sums $TMPDIR/deploy/images/qemux86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemux86/*qemux86* $DEST/machines/qemu/qemux86-lsb
        ;;
    "genericx86-lsb")
        mkdir -p $DEST/machines/genericx86-lsb
        md5sums $TMPDIR/deploy/images/genericx86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/genericx86/*genericx86* $DEST/machines/genericx86-lsb
        ;;
    "poky-tiny")
        mkdir -p $DEST/machines/qemu/qemu-tiny
        md5sums $TMPDIR/deploy/images/qemux86
        cp -R --no-dereference --preserve=links $TMPDIR/deploy/images/qemux86/*qemux86* $DEST/machines/qemu/qemu-tiny
        ;;
    "eclipse-plugin-neon")
        DIR=$WORKDIR/../scripts
        # create md5sums only for the zip files
        for x in `ls $DIR/*.zip`; do md5sum $x >> $x.md5sum; done
        mkdir -p $DEST/eclipse-plugin/neon
        cp --no-dereference --preserve=links $DIR/org.*.zip $DIR/org.*.md5sum $DEST/eclipse-plugin/neon
        ;;
    "eclipse-plugin-oxygen")
        DIR=$WORKDIR/../scripts
        # create md5sums only for the zip files
        for x in `ls $DIR/*.zip`; do md5sum $x >> $x.md5sum; done
        mkdir -p $DEST/eclipse-plugin/oxygen
        cp --no-dereference --preserve=links $DIR/org.*.zip $DIR/org.*.md5sum $DEST/eclipse-plugin/oxygen
        ;;
esac

