#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Run Auto Upgrade Helper in a directory set up by setup_auh.
#
# Called with $1 - the directory where the setup was created

if [ -z $1 ]; then
  echo "Use: $0 auh_setup_dir [publish_dir]"
  exit 1
fi

full_dir=$(readlink -e $1)

auh_dir=$full_dir/auto-upgrade-helper
poky_dir=$full_dir/poky
build_dir=$full_dir/build
sstate_dir=$full_dir/build/sstate-cache

pushd $poky_dir

# Base the upgrades on poky master
git fetch origin
git checkout -B tmp-auh-upgrades origin/master

source $poky_dir/oe-init-build-env $build_dir
$auh_dir/upgrade-helper.py -e all

if [ -n $2 ]; then
  cp -rf $build_dir/upgrade-helper/* $2
fi

popd
