#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0-only
#
PARENTDIR=`realpath $1`
BRANCH="$2"
RESULTSDIR=`realpath -m $3`
RESULTTAG=$4 # Tag to use in RESULTSDIR paths and commits
OURDIR=`dirname $0`

TIMESTAMP=`date +"%s"`

if [ -n "$RESULTTAG" ]; then
	RESULTTAG_COMMIT="$RESULTTAG: "
	RESULTTAG_PATH="$RESULTTAG"
else
	RESULTTAG_COMMIT=""
	RESULTTAG_PATH="."
fi
if [ ! -d $RESULTSDIR/$RESULTTAG_PATH/ ]; then
    mkdir -p $RESULTSDIR/$RESULTTAG_PATH/
fi

#
# CVE Checks
#
unset BB_ENV_PASSTHROUGH_ADDITIONS
unset BB_ENV_EXTRAWHITE
bitbake world --runall cve_check -R conf/distro/include/cve-extra-exclusions.inc

if [ ! -d $PARENTDIR/yocto-metrics ]; then
	git clone https://git.yoctoproject.org/yocto-metrics $PARENTDIR/yocto-metrics
else
	git -C $PARENTDIR/yocto-metrics fetch origin
fi
if [ -e tmp/log/cve/cve-summary.json ]; then
	git -C $PARENTDIR/yocto-metrics rm cve-check/$RESULTTAG_PATH/$BRANCH/*.json
	mkdir -p $PARENTDIR/yocto-metrics/cve-check/$RESULTTAG_PATH/$BRANCH
	cp tmp/log/cve/cve-summary.json $PARENTDIR/yocto-metrics/cve-check/$RESULTTAG_PATH/$BRANCH/$TIMESTAMP.json
	git -C $PARENTDIR/yocto-metrics add cve-check/$RESULTTAG_PATH/$BRANCH/$TIMESTAMP.json
	git -C $PARENTDIR/yocto-metrics commit -asm "${RESULTTAG_COMMIT}Autobuilder adding new CVE data for branch $BRANCH"
	#git -C $PARENTDIR/yocto-metrics push
	$OURDIR/cve-report.py tmp/log/cve/cve-summary.json > $RESULTSDIR/$RESULTTAG_PATH/cve-status-$BRANCH.txt
fi

mkdir -p $PARENTDIR/yocto-metrics/cve-check/$RESULTTAG_PATH/
$OURDIR/cve-generate-chartdata --json $PARENTDIR/yocto-metrics/cve-check/$RESULTTAG_PATH/cve-count-byday.json --resultsdir $PARENTDIR/yocto-metrics/cve-check/$RESULTTAG_PATH/
git -C $PARENTDIR/yocto-metrics add cve-check/$RESULTTAG_PATH/cve-count-byday.json
git -C $PARENTDIR/yocto-metrics commit -asm "${RESULTTAG_COMMIT}Autobuilder updating CVE counts"
#git -C $PARENTDIR/yocto-metrics push

cp $PARENTDIR/yocto-metrics/cve-check/$RESULTTAG_PATH/cve-count-byday.json $RESULTSDIR/$RESULTTAG_PATH/
cp $PARENTDIR/yocto-metrics/cve-check/$RESULTTAG_PATH/cve-count-byday-lastyear.json $RESULTSDIR/$RESULTTAG_PATH/

exit 0
