#!/usr/bin/env python3
#
# Iterate over a set of configurations from json.conf, calling setup-config for each one, then running the build.
#
# Called with $1 - The 'nightly' target the autobuilder is running
#             $2 - The target build directory to configure
#             $3 - The poky branch name the build is running on
#             $4 - The name of the repository the build is running on
#             $5 - The directory to publish sstate into
#             $6 - A build-appliance SRCREV to use
#             $7 - Where to publish artefacts to (or None)
#

import json
import os
import sys
import subprocess
import errno

import utils

if len(sys.argv) != 9:
    print("Incorrect number of parameters, please call as %s <nightly-target> <target-builddir> <branch-name> <repo-name> <sstate-publish-dir> 	<build-app-srcrev> <publish-dir> <error-report-url>"  % sys.argv[0])
    sys.exit(1)

target = sys.argv[1]
builddir = sys.argv[2]
branchname = sys.argv[3]
reponame = sys.argv[4]
sstate_release = sys.argv[5]
buildappsrcrev = sys.argv[6]
publish = None
if sys.argv[7] != "None":
    publish = sys.argv[7]
errorurl = None
if sys.argv[8] != "None":
    errorurl = sys.argv[8]

scriptsdir = os.path.dirname(os.path.realpath(__file__))
ourconfig = utils.loadconfig(__file__)

# Find out the number of steps this target has
maxsteps = 1
if target in ourconfig['overrides']:
    for v in ourconfig['overrides'][target]:
        if v.startswith("step"):
            n = int(v[4:])
            if n <= maxsteps:
                continue
            maxsteps = n

utils.printheader("Target task %s has %d steps" % (target, maxsteps))

finalret = 0

def flush():
    sys.stdout.flush()
    sys.stderr.flush()

lognum = 0
def logname(path):
    global lognum
    lognum += 1
    return path + "/command.log.%s" % lognum

revision = "unknown"
report = utils.ErrorReport(ourconfig, target, builddir, branchname, revision)
errordir = utils.errorreportdir(builddir)
utils.mkdir(errordir)


def bitbakecmd(builddir, cmd, report, stepnum):
    global finalret
    flush()
    log = logname(builddir)
    errordir = utils.errorreportdir(builddir)
    numreports = len(os.listdir(errordir))
    ret = subprocess.call(". ./oe-init-build-env; %s | tee %s" % (cmd, log), shell=True, cwd=builddir + "/..")
    if ret:
        utils.printheader("ERROR: Command %s failed with exit code %d, see errors above." % (cmd, ret))
        # No error report was written but the command failed so we should write one
        if len(os.listdir(errordir)) == numreports:
            report.create(cmd, stepnum, log)
        finalret = 1

bh_path, remoterepo, remotebranch, baseremotebranch = utils.getbuildhistoryconfig(ourconfig, target, reponame, branchname)
if False and bh_path:
    utils.runcmd([os.path.join(scriptsdir, "buildhistory-init"), bh_path, remoterepo, remotebranch, baseremotebranch])

for stepnum in range(maxsteps):
    # Add any layers specified
    layers = utils.getconfiglist("ADDLAYER", ourconfig, target, stepnum + 1)
    for layer in layers:
        bitbakecmd(builddir, "bitbake-layers add-layer %s" % layer, report, stepnum + 1)

    # Generate the configuration files needed for this step
    flush()
    subprocess.check_call([scriptsdir + "/setup-config", target, str(stepnum), builddir, branchname, reponame, sstate_release, buildappsrcrev])

    # Execute the targets for this configuration
    targets = utils.getconfigvar("BBTARGETS", ourconfig, target, stepnum + 1)
    if targets:
        utils.printheader("Running bitbake %s" % targets)
        bitbakecmd(builddir, "bitbake %s" % targets, report, stepnum + 1)

    # Execute the sanity targets for this configuration
    sanitytargets = utils.getconfigvar("SANITYTARGETS", ourconfig, target, stepnum + 1)
    if sanitytargets:
        utils.printheader("Running bitbake %s" % sanitytargets)
        bitbakecmd(builddir, "checkvnc; DISPLAY=:1 bitbake %s" % sanitytargets, report, stepnum + 1)

    # Remove any layers we added
    for layer in layers:
        bitbakecmd(builddir, "bitbake-layers remove-layer %s" % layer, report, stepnum + 1)

    # Run any extra commands specified
    cmds = utils.getconfiglist("EXTRACMDS", ourconfig, target, stepnum + 1)
    for cmd in cmds:
        bitbakecmd(builddir, cmd, report, stepnum + 1)

if publish:
    utils.printheader("Running publish artefacts")
    subprocess.check_call([scriptsdir + "/publish-artefacts", builddir, publish, target])

if errorurl:
    utils.printheader("Sending any error reports")
    subprocess.check_call([scriptsdir + "/upload-error-reports", builddir, errorurl])

sys.exit(finalret)

