#!/bin/bash
# Initialize Auto Upgrade Helper in a directory.
#
# Called with $1 - the directory to place the setup
CONFIG_DIR=`dirname $0`/auh-config

if [ -z $1 ]; then
  echo "Use: $0 target_dir"
  exit 1
fi

mkdir -p $1
pushd $1

git clone git://git.yoctoproject.org/poky
pushd poky
git config user.email auh@yoctoproject.org
git config user.name "Auto Upgrade Helper"
popd
git clone git://git.yoctoproject.org/auto-upgrade-helper
source poky/oe-init-build-env build
mkdir -p upgrade-helper
popd

cp $CONFIG_DIR/upgrade-helper.conf $1/build/upgrade-helper
cat $CONFIG_DIR/local.conf.append >> $1/build/conf/local.conf
