#!/bin/bash

BUILDDIR=$1
ERRORLINK=$2
#https://autobuilder.yocto.io/builders/nightly-arm/builds/804

# Need to clear parameters ready to source the environment below
shift
shift

if [ ! -e $BUILDDIR ]; then
    exit 0
fi

cd $BUILDDIR/../

if [ -d $BUILDDIR/tmp/log/error-report/ ]; then
    host=`hostname`
    echo "yp-ab-$host" > ~/.oe-send-error

    . ./oe-init-build-env
    for x in `ls $BUILDDIR/tmp/log/error-report/ | grep error_report_`; do
        send-error-report -y  -l $ERRORLINK tmp/log/error-report/$x
    done
fi

